Onion-Architecture/Controllers/AuthenticateLoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OA.Service;
using Onion_Architecture.Models;
using System.Security.Claims;

namespace Onion_Architecture.Controllers
{
    public class AuthenticateLoginController : Controller
    {
        private readonly IUserService userService;

        private readonly ITokenService tokenService;

        private readonly IConfiguration configuration;

        public AuthenticateLoginController(IUserService userService, IConfiguration configuration, ITokenService tokenService)
        {
            this.userService = userService;
            this.configuration = configuration;
            this.tokenService = tokenService;
        }

        [HttpGet]
        public IActionResult LoginUser()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult LoginUser([FromBody] UserViewModel model)
        {
            if (model is null)
            {
                return BadRequest("Invalid Client Request");
            }
            var user = userService.GetUser(model.UserName, model.Password);
            if (user is null)
            {
                return Unauthorized();
                //return BadRequest("User not found");
            }

            var claims = new[]
            {
                new Claim(ClaimTypes.Name, model.UserName),
                new Claim(ClaimTypes.Role, "User")
            };

            var accessToken = tokenService.GenerateAccessToken(claims);
            var refreshToken = tokenService.GenerateRefreshToken();

            user.RefreshToken = refreshToken;
            user.RefreshTokenExpireTime = DateTime.Now.AddSeconds(20);

            userService.SaveChanges();

            return Ok(new AuthenticatedRespone
            {
                Token = accessToken,
                RefreshToken = refreshToken
            });
        }
    }
}

Onion-Architecture/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.IdentityModel.Tokens;
using OA.Data;
using OA.Service;
using Onion_Architecture.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Web;

namespace Onion_Architecture.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService userService;

        private readonly ITokenService tokenService;

        private readonly IConfiguration configuration;

        public LoginController(IUserService userService, IConfiguration configuration, ITokenService tokenService)
        {
            this.userService = userService;
            this.configuration = configuration;
            this.tokenService = tokenService;
        }

        [HttpGet]
        public IActionResult LoginUser()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult LoginUser( UserViewModel model)
        {

            var user = Authenticate(model);
            if (user != null)
            {
                var token = Generate(user);
                return Ok(token);
                //return RedirectToAction("Index", "User");
            }
            return NotFound("User Not Found");
        }

        private object Generate(UserViewModel user)
        {
            var sercurityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration["Jwt:Key"]));
            var credentials = new SigningCredentials(sercurityKey, SecurityAlgorithms.HmacSha256);
            var claims = new[]
            {
                new Claim(ClaimTypes.NameIdentifier, user.UserName),
                new Claim("Password", user.Password),
            };
            var token = new JwtSecurityToken(configuration["Jwt:Issuer"],
                configuration["Jwt:Audience"],
                expires: DateTime.Now.AddMinutes(15),
                signingCredentials: credentials);
            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        private UserViewModel? Authenticate(UserViewModel model)
        {
            bool user = userService.CheckUser(model.UserName, model.Password);
            if (user == true)
            {
                return model;
            }
            return null;
        }
    }
}

Onion-Architecture/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using OA.Data;
using OA.Repository;
using OA.Service;
using Onion_Architecture.Models;
using Microsoft.AspNetCore.Http;
using System.Runtime.Serialization;

namespace Onion_Architecture.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        private readonly IUserInfoService userInfoService;

        public UserController(IUserService userService, IUserInfoService userInfoService)
        {
            this.userService = userService;
            this.userInfoService = userInfoService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            List<UserViewModel> model = new List<UserViewModel>();
            userService.GetAllUser().ToList().ForEach(u =>
            {
                UserInfo userInfo = userInfoService.GetUserInfo(u.Id);
                UserViewModel user = new UserViewModel
                {
                    Id = u.Id,
                    Name = $"{userInfo.FirstName} {userInfo.LastName}",
                    Email = u.Email,
                    Address = userInfo.Address
                };
                model.Add(user);
            });
            return View(model);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            UserViewModel model = new UserViewModel();
            return View("AddUser", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUser(UserViewModel model)
        {
                User user = new User
                {
                    UserName = model.UserName,
                    Password = model.Password,
                    Email = model.Email,
                    AddedDate = DateTime.UtcNow,
                    ModifiedDate = DateTime.UtcNow,
                    IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString(),
                    UserInfo = new UserInfo
                    {
                        Address = model.Address,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        AddedDate = DateTime.UtcNow,
                        ModifiedDate = DateTime.UtcNow,
                        IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString()
                    }
                };
                userService.InsertUser(user);
                if (user.Id > 0)
                {
                    return RedirectToAction("Index");
                }
            return View(model);
        }

        [HttpGet]
        public IActionResult EditUser(int? id)
        {
            UserViewModel usermodel = new UserViewModel();
            if(id.HasValue && id.Value > 0)
            {
                User user = userService.GetUser(id.Value);
                UserInfo userInfo = userInfoService.GetUserInfo(id.Value);
                usermodel.FirstName = userInfo.FirstName;
                usermodel.LastName = userInfo.LastName;
                usermodel.Address = userInfo.Address;
                usermodel.Email = user.Email;
            }
            return View("EditUser", usermodel);
        }

        [HttpPost]
        public IActionResult EditUser(UserViewModel model)
        {
            User user = userService.GetUser(model.Id);
            UserInfo userInfo = userInfoService.GetUserInfo(model.Id);
            user.Email = model.Email;
            user.ModifiedDate = DateTime.UtcNow;
            user.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            userInfo.FirstName = model.FirstName;
            userInfo.LastName = model.LastName;
            userInfo.Address = model.Address;
            userInfo.ModifiedDate = DateTime.UtcNow;
            userInfo.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            user.UserInfo = userInfo;
            userService.UpdateUser(user);
            if(user.Id >0)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult DeleteUser(UserViewModel model,long ?id)
        {
            UserInfo userInfo = userInfoService.GetUserInfo(id);
            User user = userService.GetUser(id);
            return View("DeleteUser", model);
        }

        [HttpPost]
        public IActionResult DeleteUser(long? id)
        {
            userService.DeleteUser(id);
            return RedirectToAction("Index");
        }
    }
}

Onion-Architecture/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Onion_Architecture</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Bootstheme.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Onion_Architecture</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LoginUser">Login User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AuthenticateLogin" asp-action="LoginUser">Login User with Authenticate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Onion_Architecture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>